### ISSUE TITLE
Containerize

### ISSUE THREAD

**Issue by JGarciaCondado** [compneurobilbao/ageml#36]
It would be good to containerise the software and have a docker image so that people can more easily install the software with an image that we know works.

**Comment by itellaetxe** [comment]
Created `feature_dockerize` branch.
Two dockerfiles created:
- Dockerfile -> Installs `ageml` using pip (should be stable, as the sw comes from a release)
- Dockerfile_dev -> Installs `ageml` from the main branch of the repo. Unstable, but bleeding-edge.

**Comment by itellaetxe** [comment]
TODO: Add documentation to this feature

Working on it.
